name: surf_widget_test_composer
description: Utility that simplifies widget and golden testing.
version: 0.0.1

homepage: https://github.com/surfstudio/flutter-surf-widget-test-composer
repository: https://github.com/surfstudio/flutter-surf-widget-test-composer
issue_tracker: https://github.com/surfstudio/flutter-surf-widget-test-composer/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^2.0.0