name: surf_widget_test_composer
description: Widget Test Composer is a utility package designed to simplify widget and golden testing processes using golden_toolkit package.
version: 0.0.2

homepage: https://github.com/surfstudio/flutter-surf-widget-test-composer
repository: https://github.com/surfstudio/flutter-surf-widget-test-composer
issue_tracker: https://github.com/surfstudio/flutter-surf-widget-test-composer/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^3.0.1
