name: Create Pyrus task from pull request

on:
  pull_request:
    types:
      - reopened
      - opened

jobs:
  get_package_name:
    uses: surfstudio/flutter-ci-workflows/.github/workflows/get_package_name.yml@SNP-1124_update_CI

  call_create_pyrus_task_from_pull_request:
    name: Create Pyrus task from pull request
    needs: get_package_name
    uses: surfstudio/flutter-ci-workflows/.github/workflows/new_issue_or_pr_to_pyrus_task.yml@SNP-1124_update_CI
    with:
      TYPE: PR
      PACKAGE_NAME: ${{ needs.get_package_name.outputs.package_name }}
      TITLE: ${{ github.event.pull_request.title }}
      BODY: ${{ github.event.pull_request.body }}
      LINK: ${{ github.event.pull_request.html_url }}
    secrets:
      LOGIN: ${{ secrets.PYRUS_BOT_LOGIN }}
      SECURITY_KEY: ${{ secrets.PYRUS_BOT_SECRET_KEY }}
